In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("dataset/iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
df.shape

(150, 5)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.drop(columns=['species'])
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [9]:
Y = df[['species']]
Y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [10]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,train_size=0.8)

In [11]:
X_train.to_numpy()

array([[6.4, 2.9, 4.3, 1.3],
       [5.6, 2.7, 4.2, 1.3],
       [4.9, 2.5, 4.5, 1.7],
       [5.4, 3.4, 1.7, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.9, 3.2, 4.8, 1.8],
       [5.1, 3.8, 1.5, 0.3],
       [5.7, 3. , 4.2, 1.2],
       [5.1, 3.8, 1.9, 0.4],
       [6. , 3.4, 4.5, 1.6],
       [6. , 3. , 4.8, 1.8],
       [5.8, 4. , 1.2, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [7.9, 3.8, 6.4, 2. ],
       [6.6, 2.9, 4.6, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6.5, 3. , 5.2, 2. ],
       [6.3, 2.3, 4.4, 1.3],
       [5.1, 3.7, 1.5, 0.4],
       [5.4, 3. , 4.5, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [4.8, 3.4, 1.9, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [5. , 3.4, 1.5, 0.2],
       [6.3, 2.9, 5.6, 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [5.5, 2.4, 3.7, 1. ],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.1, 2.6, 5.6, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [5.4, 3

In [12]:
Y_test.shape

(30, 1)

In [13]:
X_test.shape

(30, 4)

In [14]:
Y_train.shape

(120, 1)

In [15]:
Y_test.shape

(30, 1)

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [18]:
a=le.fit_transform(Y_train)
a

C:\Users\CS-L2-PC02\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 1, 2, 0, 2, 1, 0, 1, 0, 1, 2, 0, 0, 2, 1, 1, 2, 1, 0, 1, 2, 2,
       0, 2, 0, 2, 2, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 2, 0, 2, 2, 1,
       2, 1, 2, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 2,
       1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 2, 2, 2, 1, 1, 0, 0, 1, 2, 0, 0,
       0, 1, 2, 1, 2, 0, 2, 2, 0, 1, 2, 1, 2, 1, 1, 1, 2, 0, 1, 2, 2, 2,
       0, 2, 0, 2, 2, 0, 1, 2, 0, 0])

In [19]:
b=le.fit_transform(Y_test)
b

array([0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 2, 1, 1, 2, 2, 1, 1, 2,
       0, 2, 1, 2, 0, 1, 0, 2])

In [20]:
# tr = ColumnTransformer(transformers=[
#     ('t1',OrdinalEncoder(categories=[['setosa','versicolor','virginica']]),['species'])
# ],remainder='passthrough')

In [21]:
#tr

In [22]:
# a=tr.fit_transform(Y_train).shape
# a

In [23]:
# b=tr.fit_transform(Y_test).shape
# b

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr=LinearRegression()

In [26]:
lr.fit(X_train,a)

LinearRegression()

In [27]:
pr=lr.predict(X_test)
pr

array([ 0.08607629, -0.00563426,  1.51597932, -0.09484861, -0.03587191,
        1.15760533, -0.10337293, -0.03180844,  0.20356469,  1.65576762,
       -0.09308315, -0.14322363,  1.28156328, -0.17847727,  1.92400626,
        1.34854069,  1.17937269,  1.60974465,  2.05206375,  1.02585383,
        1.29663476,  2.05364895, -0.14993747,  2.00791529,  1.0635732 ,
        2.04629887, -0.1500276 ,  1.19629976, -0.1905325 ,  1.74909947])

In [28]:
lr.score(X_train,a)

0.9264861358213734

In [29]:
lr.score(X_test,b)

0.9397152083474842

In [30]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(b,pr)
mse

0.04052477661085783

In [31]:
np.sqrt(mse)

0.201307666547645

In [33]:
from sklearn.metrics import r2_score
r2_score(b,pr)

0.9397152083474842