In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("dataset/iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [4]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [5]:
df.shape

(150, 5)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop(columns=['species'])
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [8]:
Y = df[['species']]
Y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [9]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,train_size=0.8)

In [10]:
X_train.to_numpy()

array([[6.4, 2.8, 5.6, 2.1],
       [5.2, 2.7, 3.9, 1.4],
       [4.9, 2.5, 4.5, 1.7],
       [6.1, 2.9, 4.7, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [6.5, 3. , 5.8, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [4.9, 3.6, 1.4, 0.1],
       [6.7, 3.1, 4.4, 1.4],
       [6. , 2.2, 5. , 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [6.4, 3.2, 5.3, 2.3],
       [4.8, 3. , 1.4, 0.1],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [5.4, 3.4, 1.7, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [4.6, 3.6, 1. , 0.2],
       [7.7, 3. , 6.1, 2.3],
       [5. , 3.5, 1.6, 0.6],
       [7.9, 3.8, 6.4, 2. ],
       [6.5, 2.8, 4.6, 1.5],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 3.3, 6. , 2.5],
       [5.7, 2.8, 4.1, 1.3],
       [6.1, 3. , 4.6, 1.4],
       [5.1, 3.7, 1.5, 0.4],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 2.5, 5. , 2. ],
       [6. , 2.2, 4. , 1. ],
       [4.4, 3

In [11]:
Y_test.shape

(30, 1)

In [12]:
X_test.shape

(30, 4)

In [13]:
Y_train.shape

(120, 1)

In [14]:
Y_test.shape

(30, 1)

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder

In [16]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [17]:
a=le.fit_transform(Y_train)
a

C:\Users\CS-L2-PC02\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 1, 2, 1, 0, 2, 2, 2, 0, 1, 2, 1, 2, 0, 1, 0, 2, 0, 2, 0, 2, 0,
       2, 1, 1, 2, 1, 1, 0, 1, 0, 2, 2, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 0,
       2, 1, 1, 2, 1, 1, 0, 0, 2, 2, 0, 0, 0, 2, 2, 1, 0, 0, 2, 0, 0, 2,
       1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 2, 2, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1,
       1, 2, 1, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0,
       2, 0, 0, 2, 0, 1, 2, 1, 0, 0])

In [18]:
b=le.fit_transform(Y_test)
b

array([2, 2, 0, 0, 1, 0, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 1, 2, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1])

### #linear regression

In [19]:
#from sklearn.linear_model import LinearRegression

In [20]:
#lr=LinearRegression()

In [21]:
#lr.fit(X_train,a)

In [22]:
#lr.predict(X_test)

In [23]:
#lr.score(X_train,a)

In [24]:
#lr.score(X_test,b)

### logistic regression

In [25]:
from sklearn.linear_model import LogisticRegression


In [26]:
lgr=LogisticRegression(random_state=0)

In [27]:
lgr.fit(X_train,a)

LogisticRegression(random_state=0)

In [28]:
pred=lgr.predict(X_test)

In [29]:
pred

array([2, 2, 0, 0, 1, 0, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 1, 2, 0, 2,
       1, 0, 0, 1, 0, 1, 1, 1])

In [30]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [31]:
as_lr=accuracy_score(b,pred)
as_lr

0.9666666666666667

In [32]:
pd.DataFrame(confusion_matrix(b,pred),columns=list(range(0,3)))

0  1  2
0  12  0  0
1   0  9  1
2   0  0  8

In [33]:
from sklearn.metrics import precision_score

precision_score(b,pred,average='micro')

0.9666666666666667

In [34]:
from sklearn.metrics import recall_score
recall_score(b,pred, average='macro')

0.9666666666666667

In [35]:
from sklearn.metrics import f1_score
f1_score(b,pred,average='weighted')

0.9667698658410733

### decision tree classifier

In [36]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()

In [37]:
dtc.fit(X_train,a)

DecisionTreeClassifier()

In [38]:
pred_dtc=dtc.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [40]:
as_dtc=accuracy_score(b,pred_dtc)
as_dtc

0.9333333333333333

In [41]:
pd.DataFrame(confusion_matrix(b,pred_dtc),columns=list(range(0,3)))

0  1  2
0  12  0  0
1   0  8  2
2   0  0  8

In [42]:
precision_score(b,pred_dtc,average='micro')

0.9333333333333333

In [43]:
recall_score(b,pred_dtc, average='macro')

0.9333333333333332

In [44]:
f1_score(b,pred_dtc,average='weighted')

0.9333333333333333

### support vector classifier

In [45]:
from sklearn.svm import SVC   
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(X_train,a)

SVC(kernel='linear', random_state=0)

In [46]:
y_pred= classifier.predict(X_test) 

In [47]:
y_pred

array([2, 2, 0, 0, 1, 0, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 2, 1, 2, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1])

In [48]:
pd.DataFrame(confusion_matrix(b,y_pred),columns=list(range(0,3)))

0   1  2
0  12   0  0
1   0  10  0
2   0   0  8

In [49]:
as_svc=accuracy_score(b,y_pred)
as_svc

1.0

In [50]:
precision_score(b,y_pred,average='micro')

1.0

In [51]:
recall_score(b,y_pred, average='macro')

1.0

In [52]:
f1_score(b,y_pred,average='weighted')

1.0

In [53]:
ser1=[as_lr,as_dtc,as_svc]
ser2=['logistic regression','decision tree classifier','support vector classifier']
df=pd.DataFrame({'classifier':ser2,'accuracy score':ser1})
df

classifier  accuracy score
0        logistic regression        0.966667
1   decision tree classifier        0.933333
2  support vector classifier        1.000000