In [1]:
import numpy as np
np.__version__

'1.21.5'

# CREATE A 1-D ARRAY USING ARRAY()

In [3]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4]
int32
(4,)


# CREATE A 1-D ARRAY USING ARANGE()

In [6]:
import numpy as np
a=np.arange(1,7)
print(a)
print(a.dtype)
print(a.shape)

[1 2 3 4 5 6]
int32
(6,)


# CREATE A 2-D ARRAY USING ARRAY()

In [7]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(b.dtype)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]]
int32
(2, 4)


# CREATE A 2-D ARRAY USING ARANGE()

In [8]:
import numpy as np
a=np.arange(10).reshape(5,2) #MULTIPLY MUST RESULT SAME RANGE
print(a)
print(a.dtype)
print(a.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
int32
(5, 2)


# CREATE A 3-D ARRAY USING ARRAY()

In [12]:
import numpy as np
a=np.array(
    [
    [[1,2,5],[3,4,1]],
    [[5,6,3], [7,8,5]],
    [[9,10,6],[11,12,7]]    
     ]
)
print(a)
print(a.dtype)
print(a.shape)

[[[ 1  2  5]
  [ 3  4  1]]

 [[ 5  6  3]
  [ 7  8  5]]

 [[ 9 10  6]
  [11 12  7]]]
int32
(3, 2, 3)


# CREATE A 3-D ARRAY USING ARANGE()

In [13]:
import numpy as np
a=np.arange(1,19).reshape(3,3,2)  #MULTIPLY MUST RESULT SAME RANGE
print(a)
print()
print(a.dtype)
print(a.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]

int32
(3, 3, 2)


# CREATING ARRAY OF ONES (1-D)

In [18]:
import numpy as np
a=np.ones(10,dtype=int)
print(a)
print(a.dtype)
print(a.shape)

[1 1 1 1 1 1 1 1 1 1]
int32
(10,)


# CREATING ARRAY OF ONES(2-D)

In [19]:
import numpy as np
b=np.ones((3,3),dtype=int)
print(b)
print(a.dtype)
print(a.shape)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
int32
(10,)


# CREATING ARRAY OF ONES(3-D)

In [24]:
import numpy as np
a=np.ones((3,3,2),dtype=int)
print(a)
print(a.dtype)
print(a.shape)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
int32
(3, 3, 2)


# CREATING ARRAY OF ZEROS(1-D)

In [25]:
import numpy as np
a= np.zeros(3,dtype=np.int32)
print(a)
print(a.dtype)
print(a.shape)

[0 0 0]
int32
(3,)


# CREATING ARRAY OF ZEROS(2-D)

In [26]:
import numpy as np
a=np.zeros((3,3),dtype="int32")
print(a)
print(a.dtype)
print(a.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
int32
(3, 3)


# CREATING ARRAY OF ZEROS(3-D)

In [28]:
import numpy as np
a=np.zeros((3,3,3),dtype=int)
print(a)
print(a.dtype)
print(a.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
int32
(3, 3, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(1-D)

In [32]:
import numpy as np
a=np.random.randint(1,6,size=4) #1-10 size=reshape
print(a)
print(a.dtype)
print(a.shape)

[3 1 4 5]
int32
(4,)


# CREATE AN ARRAY WITH RANDOM NUMBERS(2-D)

In [33]:
import numpy as np
a=np.random.randint(1,11,size=(3,3))
print(a)
print(a.dtype)
print(a.shape)

[[ 8  8  2]
 [ 4  8  4]
 [ 1  2 10]]
int32
(3, 3)


# CREATE AN ARRAY WITH RANDOM NUMBERS(3-D)

In [34]:
import numpy as np
a=np.random.randint(1,11,size=(3,2,3))
print(a)
print(a.dtype)
print(a.shape)

[[[4 2 3]
  [4 2 9]]

 [[1 2 7]
  [6 1 9]]

 [[6 2 5]
  [9 5 8]]]
int32
(3, 2, 3)


# CREATE ARRAY WITH SINGLE LOW MULTIPLE HIGH

In [35]:
import numpy as np
a=np.random.randint(5,[10,20,30])
print(a)
print(a.dtype)
print(a.shape)

[ 8 11 12]
int32
(3,)


# CREATE ARRAY WITH MULTIPLE LOW SINGLE HIGH

In [36]:
import numpy as np
a=np.random.randint([10,20,30],50)
print(a)
print(a.dtype)
print(a.shape)

[24 23 35]
int32
(3,)


# CREATE 3-D ARRAY WITH MULTIPLE LOW MULTIPLE HIGH


In [37]:
import numpy as np
a=np.random.randint([1,2,3],[3,5,6],size=(3,2,3))      
print(a)
print(a.dtype)
print(a.shape)

[[[1 3 3]
  [2 3 4]]

 [[2 4 3]
  [1 4 5]]

 [[2 2 4]
  [1 3 3]]]
int32
(3, 2, 3)


# CREATE AN ARRAY USING RANDN()

In [38]:
import numpy as np
a = np.random.randn(3) #n=ANY FLOATING VALUE
print(a)
print(a.dtype)

[1.38237657 0.07293133 0.36839571]
float64


In [39]:
import numpy as np
a = np.random.randn(3,3)
print(a)

[[-0.87766483 -0.57595972  0.73457371]
 [-0.54251247  0.04365172  0.08215135]
 [ 0.62916341 -0.66860207  1.72637068]]


# CREATE AN ARRAY USING RAND()

In [40]:
import numpy as np
a = np.random.rand(3,3)
print(a)
print(a.dtype)

[[0.39526042 0.8253705  0.71064769]
 [0.9550491  0.67821205 0.9337468 ]
 [0.76858927 0.35050862 0.27117696]]
float64


In [41]:
import numpy as np
a = np.random.rand(3,2,2)
print(a)
print(a.dtype)

[[[0.84809285 0.87732849]
  [0.96243753 0.54065067]]

 [[0.9297484  0.95638831]
  [0.00302923 0.33572276]]

 [[0.73728646 0.53053052]
  [0.94650649 0.58922954]]]
float64


# POSITIVE INDEXING IN ARRAY

In [42]:
#ARRAY IN 1-D
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[3])

4


In [43]:
#ARRAY IN 2-D
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1,2])
print(arr[0,1])

6
2


In [44]:
#ARRAY IN 3-D
import numpy as np
arr=np.array([[[1,2,3],[1,2,3]],[[1,1,1],[2,2,2]],[[3,8,3],[4,9,4]]])
print(arr[2,0,1])
print(arr[2,1,1])

8
9


# NEGATIVE INDEXING IN ARRAY


In [45]:
#ARRAY IN 2-D
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[11,12,13],[14,15,16]])
print(arr[-1,-3])
print(arr[-4,-2])
print(arr[-2,-2])

14
2
12


In [46]:
#ARRAY IN 3-D
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])
#print(arr)
print(arr[-3,-2,-2])

2


# MIX (+,-,+)

In [47]:
#ARRAY IN 3-D
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[1,8,1],[2,5,2]],[[3,3,3],[4,4,4]]])
print(arr[-2,-1,-2])
print(arr[0,-1,2])
print(arr[1,-2,1])
print(arr[1,-1,1])
print(arr[-3,-2,1])

5
6
8
5
2


# NUMPY ARRAY SLICING

Slice elements from index 1 to index 5 from the following array :

In [48]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[1:5])

[2 3 4 5]


Slice elements from index 4 to the end of the array

In [49]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


Slice elements from the beginning to index 4(not included)

In [50]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


# NEGATIVE SLICING

Slice from the index 3 from the end to index 1 from the end

In [51]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


Return every other element from index 1 to index 5

In [57]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[-1:-5:-2])

[7 5]


In [ ]:
# Return every other element from the entire array

In [58]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
print(arr[::-2])

[7 5 3 1]


# SLICING 2-D ARRAY

From the second element,slice elements from index 1 to index 4 (not included):

In [59]:
import numpy as np
arr=np.array([[1,2,3,4,5],[4,5,6,7,8]])
print(arr[1,1:4])

[5 6 7]


From both arrays ,return index 2

In [60]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


From both elements ,slice index 1 to index 4 (not included),this wll return a 2-D array:

In [61]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:,1:4])

[[2 3 4]
 [7 8 9]]
