In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('dataset/cars.csv')

In [3]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['fuel'].value_counts()

Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: fuel, dtype: int64

## 1. OneHotEncoding using Pandas

In [5]:
pd.get_dummies(df,columns=['fuel'])

brand  km_driven                 owner  selling_price  fuel_CNG  \
0      Maruti     145500           First Owner         450000         0   
1       Skoda     120000          Second Owner         370000         0   
2       Honda     140000           Third Owner         158000         0   
3     Hyundai     127000           First Owner         225000         0   
4      Maruti     120000           First Owner         130000         0   
...       ...        ...                   ...            ...       ...   
8123  Hyundai     110000           First Owner         320000         0   
8124  Hyundai     119000  Fourth & Above Owner         135000         0   
8125   Maruti     120000           First Owner         382000         0   
8126     Tata      25000           First Owner         290000         0   
8127     Tata      25000           First Owner         290000         0   

      fuel_Diesel  fuel_LPG  fuel_Petrol  
0               1         0            0  
1               1         0            0  
2               0         0            1  
3               1         0            0  
4               0         0            1  
...           ...       ...          ...  
8123            0         0            1  
8124            1         0            0  
8125            1         0            0  
8126            1         0            0  
8127            1         0            0  

[8128 rows x 8 columns]

https://towardsdatascience.com/encoding-categorical-variables-one-hot-vs-dummy-encoding-6d5b9c46e2db

## 2. K-1 OneHotEncoding

In [6]:
df1 = pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)
df1

brand  km_driven  selling_price  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0      Maruti     145500         450000            1         0            0   
1       Skoda     120000         370000            1         0            0   
2       Honda     140000         158000            0         0            1   
3     Hyundai     127000         225000            1         0            0   
4      Maruti     120000         130000            0         0            1   
...       ...        ...            ...          ...       ...          ...   
8123  Hyundai     110000         320000            0         0            1   
8124  Hyundai     119000         135000            1         0            0   
8125   Maruti     120000         382000            1         0            0   
8126     Tata      25000         290000            1         0            0   
8127     Tata      25000         290000            1         0            0   

      owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                              0                   0                     0   
1                              0                   1                     0   
2                              0                   0                     0   
3                              0                   0                     0   
4                              0                   0                     0   
...                          ...                 ...                   ...   
8123                           0                   0                     0   
8124                           1                   0                     0   
8125                           0                   0                     0   
8126                           0                   0                     0   
8127                           0                   0                     0   

      owner_Third Owner  
0                     0  
1                     0  
2                     1  
3                     0  
4                     0  
...                 ...  
8123                  0  
8124                  0  
8125                  0  
8126                  0  
8127                  0  

[8128 rows x 10 columns]

## 3. OneHotEncoding using Sklearn

In [7]:
# from sklearn.model_selection import train_test_split
# X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [8]:
df.head()

brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe = OneHotEncoder(drop='first', sparse=False)

In [11]:
df2 = ohe.fit_transform(df[['fuel','owner']])

In [12]:
df2

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [13]:
df2.shape

(8128, 7)

In [14]:
#np.hstack((df[['brand','km_driven']].values,df2))

## 4. OneHotEncoding with Top Categories

In [15]:
counts = df['brand'].value_counts()
counts

Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: brand, dtype: int64

In [16]:
df['brand'].nunique()
threshold = 50

In [17]:
repl = counts[counts <= threshold].index

In [18]:
pd.get_dummies(df['brand'].replace(repl, 'other')).sample(5)

BMW  Chevrolet  Datsun  Ford  Honda  Hyundai  Jaguar  Mahindra  Maruti  \
1463    0          0       0     0      0        0       0         1       0   
1501    0          0       0     0      0        0       0         0       1   
3664    0          0       0     0      0        1       0         0       0   
16      0          0       0     0      0        0       0         0       1   
4771    0          0       0     0      0        1       0         0       0   

      Mercedes-Benz  Nissan  Renault  Skoda  Tata  Toyota  Volkswagen  Volvo  \
1463              0       0        0      0     0       0           0      0   
1501              0       0        0      0     0       0           0      0   
3664              0       0        0      0     0       0           0      0   
16                0       0        0      0     0       0           0      0   
4771              0       0        0      0     0       0           0      0   

      other  
1463      0  
1501      0  
3664      0  
16        0  
4771      0

1. https://www.naukri.com/learning/articles/one-hot-encoding-for-multi-categorical-variables/

# LABEL ENCODER

https://www.mygreatlearning.com/blog/label-encoding-in-python/

In [19]:
df = pd.read_csv('dataset/customer.csv')
  
df.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [20]:
df.shape

(50, 5)

In [21]:
df['purchased'].unique()

array(['No', 'Yes'], dtype=object)

In [22]:
from sklearn import preprocessing
  

label_encoder = preprocessing.LabelEncoder()
  
df['purchased']= label_encoder.fit_transform(df['purchased'])
  
df['purchased'].unique()

array([0, 1])

In [23]:
df.head()

age  gender   review education  purchased
0   30  Female  Average    School          0
1   68  Female     Poor        UG          0
2   70  Female     Good        PG          0
3   72  Female     Good        PG          0
4   16  Female  Average        UG          0

# COLUMNS TRANSFORMATION

In [24]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

In [25]:
ohe=OneHotEncoder()
imp=SimpleImputer()

In [26]:
ct=make_column_transformer(
    (ohe,['review','education']),
    (imp,['age']),
    remainder='passthrough')

In [27]:
ct.fit_transform(df)

array([[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 30.0, 'Female', 0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 68.0, 'Female', 0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 70.0, 'Female', 0],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 72.0, 'Female', 0],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 16.0, 'Female', 0],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 31.0, 'Female', 1],
       [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 18.0, 'Male', 0],
       [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 60.0, 'Female', 1],
       [1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 65.0, 'Female', 0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 74.0, 'Male', 1],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 98.0, 'Female', 1],
       [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 74.0, 'Male', 1],
       [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 51.0, 'Male', 0],
       [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 57.0, 'Female', 0],
       [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 15.0, 'Male', 1],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 75.0, 'Male', 0],
       [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 59.0, 'Male', 1],
       [0.0, 0.0, 1.0, 0.0, 