# Panda series

In [4]:
import pandas as pd
ser1=pd.Series([10,20,30,40,50])
print(ser1)


0    10
1    20
2    30
3    40
4    50
dtype: int64


In [6]:
import pandas as pd
ser1=pd.Series([10,20,30,40],dtype=float)
print(ser1)

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float64


In [7]:
import pandas as pd
ser1=pd.Series([10,20,30,40,50],index=["first","second","third","fourth","fifth"])
print(ser1)


first     10
second    20
third     30
fourth    40
fifth     50
dtype: int64


In [11]:
import pandas as pd
ser1=pd.Series([1,2,3,4,5])
print(ser1)
i=pd.Index(["frist","second","third","fourth","fifth"])
ser1=pd.Series([1,2,3,4,5],index=i)
print(ser1)

0    1
1    2
2    3
3    4
4    5
dtype: int64
frist     1
second    2
third     3
fourth    4
fifth     5
dtype: int64


In [12]:
import pandas as pd
ser1=pd.Series({"first":1,"second":2,"third":3,"fourth":4})
print(ser1)

first     1
second    2
third     3
fourth    4
dtype: int64


# Data Frames

In [1]:
import numpy as np
import pandas as pd
arr = np.arange(0,9).reshape(3,3)
print(arr)
df=pd.DataFrame(arr,index=['a','b','c'],columns=['A','B','C'])
print(df)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
   A  B  C
a  0  1  2
b  3  4  5
c  6  7  8


In [8]:
import numpy as np
import pandas as pd
arr=np.array([[23,24,20,19],[20,24,25,21],[19,22,23,18]])
df=pd.DataFrame(arr, index = ["Rahul","Krishna","Abhinav"], columns=["OSA","Python","SE","Java"])
print(df)

         OSA  Python  SE  Java
Rahul     23      24  20    19
Krishna   20      24  25    21
Abhinav   19      22  23    18


In [9]:
import numpy as np
import pandas as pd
ser1=pd.Series([23,20,19])
ser2=pd.Series([20,25,23,20])
print(pd.DataFrame({"OSA":ser1,"Pyhton":ser2}))

    OSA  Pyhton
0  23.0      20
1  20.0      25
2  19.0      23
3   NaN      20


# creating DataFrame containing information about cities.

In [11]:
import numpy as np
import pandas as pd
i=pd.Index(["karnataka","Maharashtra","Gujarat"])
#print(i)
pop=pd.Series(['6.72','12.54','7.0'],index=i,name="population")
print(pop)
cap=pd.Series(["Bangalore","Mumbai","Gandhinagar"],index=i,name="capital")
#print(cap)
#df=pd.DataFrame([pop,cap]) #will not display in proper fromat
#df=pd.DataFrame([pop,cap]).T #will display in propoer format but columns name missing
df=pd.DataFrame({"population":pop, "capital":cap})
#df=pd.DataFrame([['6.72',"Bangalore"],['12.54',"Mumbai"],['7.0',"gnadhinagar"]],index=["Karnataka","Maharashtra","Gujarat"] , columns=['population','capital'])
#print(df)


karnataka       6.72
Maharashtra    12.54
Gujarat          7.0
dtype: object


# How to add a new Data to a Series

In [6]:
import numpy as np
import pandas as pd
#print(pop)
pop.append(pd.Series({"Tamilnadu":8.9}))
#print(pop)


C:\Users\CS-L2-PC02\AppData\Local\Temp\ipykernel_11912\3326186990.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  pop.append(pd.Series({"Tamilnadu":8.9}))


karnataka       6.72
Maharashtra    12.54
Gujarat          7.0
Tamilnadu        8.9
dtype: object

method 1

In [8]:
import numpy as np
import pandas as pd
i=pd.Index(["karnataka","maharashtra","gujarat"])
df=pd.DataFrame([['6.72',"bangalore"],['12.54',"mumbai"],['7.0',"gandhinagar"]],index=i,columns=['population','capital'])
#print(df)
print(df.append(pd.DataFrame([['8.9','chennai'],['12.5','hydrabad']],index=['tamilnadu','andhrapadesh'],columns=["population","capital"])))

             population      capital
karnataka          6.72    bangalore
maharashtra       12.54       mumbai
gujarat             7.0  gandhinagar
tamilnadu           8.9      chennai
andhrapadesh       12.5     hydrabad


C:\Users\CS-L2-PC02\AppData\Local\Temp\ipykernel_11912\1276740331.py:6: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame([['8.9','chennai'],['12.5','hydrabad']],index=['tamilnadu','andhrapadesh'],columns=["population","capital"])))


method 2

In [7]:
import numpy as np
import pandas as pd
i=pd.Index(['karnataka','maharashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7,0'],index=i,name="population")
cap=pd.Series(['bangalore','mumbai','gandhinagar'],index=i,name="capital")
df=pd.DataFrame({"population":pop,"capital":cap})
print(df)
print("\n")
print(df.append(pd.DataFrame({"population":pd.Series({"tamilnadu":8.9,"andhara pradsh":12.6}),"capital":pd.Series({"tamilnadu":"chennai","andhara pradsh":"hydrabad"})})))

            population      capital
karnataka         6.72    bangalore
maharashtra      12.54       mumbai
Gujarat            7,0  gandhinagar


               population      capital
karnataka            6.72    bangalore
maharashtra         12.54       mumbai
Gujarat               7,0  gandhinagar
tamilnadu             8.9      chennai
andhara pradsh       12.6     hydrabad


C:\Users\CS-L2-PC02\AppData\Local\Temp\ipykernel_11912\2437754552.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  print(df.append(pd.DataFrame({"population":pd.Series({"tamilnadu":8.9,"andhara pradsh":12.6}),"capital":pd.Series({"tamilnadu":"chennai","andhara pradsh":"hydrabad"})})))


# concat new column to DataFrame:

In [9]:
import numpy as np  
import pandas as pd
i=pd.Index(['karnataka','mahrashtra','Gujarat'])
pop=pd.Series(['6.72','12.54','7.0'],index=i,name="population")
cap=pd.Series(['Bangalore','Mumbai','gandhinagar'],index=i,name="capital")
df=pd.DataFrame({"population":pop,"capital":cap})
#print(df)
#print("\n\n")
df1=pd.concat([df,pd.DataFrame({"  area":pd.Series(['2.1','3.1','5.5'],index=pop.index),"cm":pd.Series(['Bomai','Shinde','Patel'],index=pop.index)})],axis=1)
#df1.to_csv("cities.csv")
#print(df1)
df1


population      capital   area      cm
karnataka        6.72    Bangalore    2.1   Bomai
mahrashtra      12.54       Mumbai    3.1  Shinde
Gujarat           7.0  gandhinagar    5.5   Patel

# Subsetting

In [13]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame


In [14]:
srs = Series(np.arange(5), index=["alpha","beta","gama","delta","elipson"])
srs

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32

In [15]:
srs[:2]

alpha    0
beta     1
dtype: int32

In [19]:
srs[["beta","delta"]]

beta     1
delta    3
dtype: int32

In [17]:
srs["beta":"delta"]

beta     1
gama     2
delta    3
dtype: int32

In [20]:
print(srs)
srs[srs > 3]

alpha      0
beta       1
gama       2
delta      3
elipson    4
dtype: int32


elipson    4
dtype: int32

In [21]:
srs > 3

alpha      False
beta       False
gama       False
delta      False
elipson     True
dtype: bool

In [22]:
srs2 = Series(["zero","one","two","three","four"], index=[3,2,4,0,1])
srs2

3     zero
2      one
4      two
0    three
1     four
dtype: object

In [23]:
srs2[2:4]    #Ambiguous

4      two
0    three
dtype: object

In [24]:
srs2.iloc[1:4]

2      one
4      two
0    three
dtype: object

In [25]:
srs2.loc[3:0]

3     zero
2      one
4      two
0    three
dtype: object

In [26]:
df = DataFrame(np.arange(21).reshape(7,3), columns=['AAA','BBB','CCC'], index=["alpha","beta","gama","delta","epsilon","zeta","eta"])
df

AAA  BBB  CCC
alpha      0    1    2
beta       3    4    5
gama       6    7    8
delta      9   10   11
epsilon   12   13   14
zeta      15   16   17
eta       18   19   20

In [27]:
df.AAA

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [28]:
df['AAA']

alpha       0
beta        3
gama        6
delta       9
epsilon    12
zeta       15
eta        18
Name: AAA, dtype: int32

In [29]:
df[['BBB','CCC']]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [30]:
df.iloc[1:3, 1:2]

BBB
beta    4
gama    7

In [31]:
df.loc['beta':'delta', 'BBB':'CCC']

BBB  CCC
beta     4    5
gama     7    8
delta   10   11

In [32]:
df.iloc[:, 1:3]

BBB  CCC
alpha      1    2
beta       4    5
gama       7    8
delta     10   11
epsilon   13   14
zeta      16   17
eta       19   20

In [33]:
df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']]

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [34]:
df2 = df.iloc[:, 1:3].loc[['alpha', 'gama', 'zeta']].copy()
df2

BBB  CCC
alpha    1    2
gama     7    8
zeta    16   17

In [35]:
df2['CCC'] = Series({'alpha':11, 'gama':18, 'zeta':5})
df2

BBB  CCC
alpha    1   11
gama     7   18
zeta    16    5

In [36]:
df2.iloc[1, 1] = 2
df2

BBB  CCC
alpha    1   11
gama     7    2
zeta    16    5

In [37]:
df2.iloc[:, 1] = 0
df2

BBB  CCC
alpha    1    0
gama     7    0
zeta    16    0