In [10]:
import numpy as nm  
import matplotlib.pyplot as mtp  
import pandas as pd  
  
#importing datasets  
data_set= pd.read_csv('dataset/data.csv')  
data_set


User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [13]:
x= data_set.iloc[:, [2,3]].values  
y= data_set.iloc[:, 4].values  
#print(x)
#print(y)

In [14]:
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  


In [15]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test) 

In [16]:
from sklearn.svm import SVC   
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train, y_train)  

SVC(kernel='linear', random_state=0)

In [17]:
y_pred= classifier.predict(x_test)  

In [18]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [19]:
from sklearn.metrics import confusion_matrix  
confusion_matrix(y_test, y_pred)  

array([[66,  2],
       [ 8, 24]], dtype=int64)

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)


0.9

In [23]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred,average='micro')

0.9

In [28]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred, average='macro')

0.8602941176470589

In [29]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred,average='weighted')

0.8969402622632345

In [84]:
df = pd.read_csv("dataset/iris.csv")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [85]:
from sklearn.model_selection import train_test_split

In [88]:
x = df.drop(columns=['species'])
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [92]:
y = df[['species']]
y

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [103]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8)

In [104]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [105]:
a=le.fit_transform(y_train)
a

C:\Users\CS-L2-PC02\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 2, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 2, 2, 1, 1,
       2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 0, 2, 1, 2, 2, 1, 1, 2, 0, 1, 0, 0,
       2, 2, 1, 0, 2, 0, 2, 1, 0, 0, 2, 0, 0, 2, 2, 1, 0, 2, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1, 2, 0, 1, 0, 2, 2,
       2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 2, 1, 2, 0, 0, 2])

In [106]:
b=le.fit_transform(y_test)
b

array([0, 1, 2, 0, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 0, 1, 0, 2, 0, 0, 1, 0,
       1, 1, 2, 1, 2, 2, 1, 0])

In [107]:
from sklearn.svm import SVC   
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train,a)

SVC(kernel='linear', random_state=0)

In [108]:
y_pred= classifier.predict(x_test) 

In [110]:
y_pred

array([0, 1, 2, 0, 2, 0, 1, 2, 2, 2, 1, 2, 2, 2, 0, 2, 0, 2, 0, 0, 1, 0,
       1, 1, 2, 1, 2, 2, 1, 0])

In [112]:
from sklearn.metrics import confusion_matrix  
confusion_matrix(b, y_pred)  

array([[ 9,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 12]], dtype=int64)

In [113]:
from sklearn.metrics import accuracy_score
accuracy_score(b, y_pred)

0.9666666666666667

In [114]:
from sklearn.metrics import precision_score
precision_score(b, y_pred,average='micro')

0.9666666666666667

In [115]:
from sklearn.metrics import recall_score
recall_score(b, y_pred, average='macro')

0.9629629629629629

In [116]:
from sklearn.metrics import f1_score
f1_score(b, y_pred,average='weighted')

0.9663529411764706