In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [4]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [5]:
df.drop(["PassengerId","Name","Ticket","Cabin"],axis = 1,inplace=True)

In [6]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0.0       3    male  22.0      1      0   7.2500        S
1         NaN       1  female  38.0      1      0  71.2833        C
2         NaN       3  female   NaN      0      0      NaN        S
3         NaN       1  female  35.0      1      0  53.1000        S
4         0.0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886       0.0       2    male  27.0      0      0  13.0000        S
887       1.0       1  female  19.0      0      0  30.0000        S
888       0.0       3  female   NaN      1      2  23.4500        S
889       1.0       1    male  26.0      0      0  30.0000        C
890       0.0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [8]:
df=df.drop(columns='Fare')

In [9]:
df

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         NaN       1  female  38.0      1      0        C
2         NaN       3  female   NaN      0      0        S
3         NaN       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female   NaN      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  887 non-null    float64
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       713 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Embarked  889 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [11]:
df.fillna(method='ffill',inplace=True)

In [12]:
df

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0.0       3    male  22.0      1      0        S
1         0.0       1  female  38.0      1      0        C
2         0.0       3  female  38.0      0      0        S
3         0.0       1  female  35.0      1      0        S
4         0.0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
886       0.0       2    male  27.0      0      0        S
887       1.0       1  female  19.0      0      0        S
888       0.0       3  female  19.0      1      2        S
889       1.0       1    male  26.0      0      0        C
890       0.0       3    male  32.0      0      0        Q

[891 rows x 7 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    float64
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       891 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [14]:
x=df.iloc[:,1:7]
x

Pclass     Sex   Age  SibSp  Parch Embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  38.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female  19.0      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[891 rows x 6 columns]

In [15]:
y=df.iloc[:,0]
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
886    0.0
887    1.0
888    0.0
889    1.0
890    0.0
Name: Survived, Length: 891, dtype: float64

In [16]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer

In [17]:
ohe=OneHotEncoder()
imp=SimpleImputer()

In [18]:
ct=make_column_transformer(
    (ohe,['Sex','Embarked']),
    #(imp,['age']),
    remainder='passthrough')

In [19]:
x=ct.fit_transform(x)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [22]:
x_train

array([[ 1.,  0.,  1., ..., 24.,  0.,  2.],
       [ 0.,  1.,  0., ..., 31.,  0.,  0.],
       [ 0.,  1.,  1., ..., 31.,  1.,  1.],
       ...,
       [ 0.,  1.,  0., ..., 26.,  0.,  0.],
       [ 1.,  0.,  0., ..., 36.,  1.,  0.],
       [ 0.,  1.,  0., ..., 60.,  1.,  1.]])

In [23]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()

In [24]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [25]:
pred=dtc.predict(x_test)
pred

array([0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0.,
       0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 0.])

In [26]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('accuracy of decision tree',accuracy_score(y_test,pred))

accuracy of decision tree 0.7821229050279329


In [28]:
from sklearn.svm import SVC   
classifier = SVC(kernel='linear', random_state=0)  
classifier.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

In [29]:
y_pred= classifier.predict(x_test) 

In [30]:
y_pred

array([0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 0.])

In [31]:
from sklearn.metrics import confusion_matrix  
confusion_matrix(y_test, y_pred)

array([[92, 19],
       [20, 48]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7821229050279329

In [33]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred,average='micro')

0.7821229050279329