In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dataset/titanic.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1       0.0       3   
1            2       NaN       1   
2            3       NaN       3   
3            4       NaN       1   
4            5       0.0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female   NaN      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282      NaN   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     887 non-null    float64
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          713 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         888 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


In [4]:
df.isnull().sum()

PassengerId      0
Survived         4
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             3
Cabin          687
Embarked         2
dtype: int64

In [5]:
df.drop(["PassengerId","Name","Ticket","Cabin"],axis = 1,inplace=True)

In [6]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0.0       3    male  22.0      1      0   7.2500        S
1         NaN       1  female  38.0      1      0  71.2833        C
2         NaN       3  female   NaN      0      0      NaN        S
3         NaN       1  female  35.0      1      0  53.1000        S
4         0.0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886       0.0       2    male  27.0      0      0  13.0000        S
887       1.0       1  female  19.0      0      0  30.0000        S
888       0.0       3  female   NaN      1      2  23.4500        S
889       1.0       1    male  26.0      0      0  30.0000        C
890       0.0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [7]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [8]:
x = df.drop(columns = ["Survived"])
x

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female   NaN      0      0      NaN        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [9]:
y = df[["Survived"]]
y

Survived
0         0.0
1         NaN
2         NaN
3         NaN
4         0.0
..        ...
886       0.0
887       1.0
888       0.0
889       1.0
890       0.0

[891 rows x 1 columns]

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y , test_size = 0.2,train_size = 0.8)

In [43]:
x_train.to_numpy


<bound method DataFrame.to_numpy of      Pclass     Sex   Age  SibSp  Parch     Fare Embarked
246       3  female  25.0      0      0   7.7750        S
50        3    male   7.0      4      1  39.6875        S
796       1  female  49.0      0      0  25.9292        S
228       2    male  18.0      0      0  13.0000        S
84        2  female  17.0      0      0  10.5000        S
..      ...     ...   ...    ...    ...      ...      ...
56        2  female  21.0      0      0  10.5000        S
840       3    male  20.0      0      0   7.9250        S
851       3    male  74.0      0      0   7.7750        S
225       3    male  22.0      0      0   9.3500        S
378       3    male  20.0      0      0   4.0125        C

[712 rows x 7 columns]>

In [44]:
x_test.to_numpy


<bound method DataFrame.to_numpy of      Pclass     Sex   Age  SibSp  Parch      Fare Embarked
676       3    male  24.5      0      0    8.0500        S
436       3  female  21.0      2      2   34.3750        S
318       1  female  31.0      0      2  164.8667        S
812       2    male  35.0      0      0   10.5000        S
733       2    male  23.0      0      0   13.0000        S
..      ...     ...   ...    ...    ...       ...      ...
124       1    male  54.0      0      1   77.2875        S
393       1  female  23.0      1      0  113.2750        C
511       3    male   NaN      0      0    8.0500        S
206       3    male  32.0      1      0   15.8500        S
815       1    male   NaN      0      0    0.0000        S

[179 rows x 7 columns]>

In [45]:
ytrain=y_train.to_numpy

In [46]:
ytrain

<bound method DataFrame.to_numpy of      Survived
246       0.0
50        0.0
796       1.0
228       0.0
84        1.0
..        ...
56        1.0
840       0.0
851       0.0
225       0.0
378       0.0

[712 rows x 1 columns]>

In [47]:
y_test.to_numpy


<bound method DataFrame.to_numpy of      Survived
676       0.0
436       0.0
318       1.0
812       0.0
733       0.0
..        ...
124       0.0
393       1.0
511       0.0
206       0.0
815       0.0

[179 rows x 1 columns]>

In [48]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         175
SibSp         0
Parch         0
Fare          0
Embarked      0
dtype: int64

In [49]:
df.dropna(subset = ["Survived","Fare","Embarked"],inplace = True)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 883 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  883 non-null    float64
 1   Pclass    883 non-null    int64  
 2   Sex       883 non-null    object 
 3   Age       708 non-null    float64
 4   SibSp     883 non-null    int64  
 5   Parch     883 non-null    int64  
 6   Fare      883 non-null    float64
 7   Embarked  883 non-null    object 
dtypes: float64(3), int64(3), object(2)
memory usage: 62.1+ KB


In [51]:
df.sample()

Survived  Pclass   Sex  Age  SibSp  Parch    Fare Embarked
524       0.0       3  male  NaN      0      0  7.2292        C

In [52]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [53]:
tr = ColumnTransformer(transformers = [
    ('t1',SimpleImputer(),["Age"]),
    ('t2',OneHotEncoder(drop = "first",sparse=False),["Sex","Embarked"])
],remainder = "passthrough")

In [54]:
tr

ColumnTransformer(remainder='passthrough',
                  transformers=[('t1', SimpleImputer(), ['Age']),
                                ('t2',
                                 OneHotEncoder(drop='first', sparse=False),
                                 ['Sex', 'Embarked'])])

In [55]:
trs = ColumnTransformer(transformers = [
    ('t1',SimpleImputer(),["Survived"])
],remainder = "passthrough")

In [56]:
s=trs.fit_transform(y_train)
s

array([[0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.        ],
       [1.        ],
       [0.        ],
       [0.   

In [57]:
a=tr.fit_transform(x_train)
a

array([[25.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  7.775 ],
       [ 7.    ,  1.    ,  0.    , ...,  4.    ,  1.    , 39.6875],
       [49.    ,  0.    ,  0.    , ...,  0.    ,  0.    , 25.9292],
       ...,
       [74.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  7.775 ],
       [22.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  9.35  ],
       [20.    ,  1.    ,  0.    , ...,  0.    ,  0.    ,  4.0125]])

In [58]:
b=tr.fit_transform(x_test)
b

array([[ 24.5       ,   1.        ,   0.        , ...,   0.        ,
          0.        ,   8.05      ],
       [ 21.        ,   0.        ,   0.        , ...,   2.        ,
          2.        ,  34.375     ],
       [ 31.        ,   0.        ,   0.        , ...,   0.        ,
          2.        , 164.8667    ],
       ...,
       [ 28.89874074,   1.        ,   0.        , ...,   0.        ,
          0.        ,   8.05      ],
       [ 32.        ,   1.        ,   0.        , ...,   1.        ,
          0.        ,  15.85      ],
       [ 28.89874074,   1.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ]])

In [27]:
y_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 712 entries, 246 to 378
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  709 non-null    float64
dtypes: float64(1)
memory usage: 11.1 KB


In [28]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [29]:
lr.fit(a,s)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').